### ISSUE TITLE
add ability to get device name from server

### ISSUE THREAD

**Issue by doronzRumble** [calabash/calabash-ios-server#228]
add ability to get device name from server

this can be done using the libImobileDevice library

**Comment by jmoody** [comment]
The server could easily report this information at runtime.

libimobiledevice is useful _before_ launching.  Because of conflicting licenses, we cannot link to libimobiledevice.

**Comment by jmoody** [comment]
So I guess the question is, do you need the device name _before_ launching?  Or would having the device name _after_ launch be sufficient?

**Comment by doronzRumble** [comment]
During runtime is sufficient. i could always use libImobileDevice to get it prior to launching calabash-ios server
