### ISSUE TITLE
Xcode 7 GM touch coordinates are off on iPhone 6 and 6+

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios-server#238]
ATTN @rasmuskl @john7doe

**Comment by john7doe** [comment]
For me it only looks like a problem with simulators. The test that fail for me on simulator are working on my 6+ with ios9

**Comment by jmoody** [comment]
Can you tell if the app on the simulator is in Zoomed mode?

**Comment by john7doe** [comment]
I do not think it is in zoomed mode. Btw it is this this app: https://github.com/xamarin/test-cloud-test-apps/blob/master/uitest-test-apps/XTCiOSSample.app.zip

**Comment by jmoody** [comment]
I cannot reproduce in iOS 9 6 and 6 Plus Simulators.

- [x] CalSmokeApp
- [x] CalWebApp

I wonder if this a problem with the Agent version.

I will now try to reproduce with the Sample you passed to me @john7doe

**Comment by jmoody** [comment]
Reproduced on both iOS 9 6 and 6+ Simulators with your sample app.

This makes me think this app is not optimized for 6 and 6+ screen sizes.

I _thought_ the server could handle this, but maybe it cannot.

Let me have a look at the XS solution.

Let me take a look at the

**Comment by jmoody** [comment]
@john7doe @rasmuskl @krukow 

As far as I can tell, the app is not ready for 6 and 6+ screens sizes.

1. Needs launch images for screen sizes or it needs a LaunchScreen{.xib|.storyboard}.
2. Needs 3x image assets (not sure if there are any).

**Comment by jmoody** [comment]
@john7doe @rasmuskl @krukow 

Discovered at least one problem on the server.  Investigating.
