### ISSUE TITLE
implement send-app-to-background as a server route

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios-server#254]
* **Xcode 7 GM/iOS 9 send_app_to_background is broken** [#836](https://github.com/calabash/calabash-ios/issues/836)
* [C# solution(http://forums.xamarin.com/discussion/comment/155864#Comment_155864)
* [Apple Forums Post](https://forums.developer.apple.com/message/59798)
* radar://22416851

**Comment by jmoody** [comment]
The forum post only shows how to suspend the app, not bring it back from the background state.

**Comment by doronzRumble** [comment]
hey @jmoody, was this fixed? your last comment states the post doesnt show how to get the app back from background state but the label is fixed.
also, do you maybe know why we have the time limit of 60 seconds?

**Comment by jmoody** [comment]
It is implemented in the server, but not in the client.  This will be part of release 0.17.

The time limit is based on the UIAutomation API limit.
