### ISSUE TITLE
Xcode 7.1: `make framework` does not find arm library on every system

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios-server#279]
Reported by @stopiccot

Changing the ARM_LIBRARY_XC7 fixes the problem:

```
"${ARM_BUILD_DIR}/Build/Intermediates/ArchiveIntermediates/${XC_TARGET}/IntermediateBuildFilesPath/UninstalledProducts/${LIBRARY_NAME}"`
"${ARM_BUILD_DIR}/Build/Intermediates/ArchiveIntermediates/${XC_TARGET}/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/${LIBRARY_NAME}"`
```

**Comment by jmoody** [comment]
Discovered the problem - the paths are indeed incorrect on the master branch.

Fixed on the develop branch.

Thanks @stopiccot!

**Comment by jmoody** [comment]
Well, now I have no idea what is going on.

There are definitely problems with the build system.

**Comment by stopiccot** [comment]
Obviously I don't see the whole picture and may be missing something, but I strongly advice switching to framework building by Xcode. This way you don't need to guess where yet-another-new-Xcode-in-which-Apple-changed-everything-again stores files.

**Comment by jmoody** [comment]
It has been proposed and I am interested.   I did some framework exploration recently and found that there were some downsides.

 This method has served us pretty well.  And this is the first time we've encountered something like this.
