### ISSUE TITLE
Xcode 7.2: builds simulator dylib to Debug-iphoneos directory

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios-server#303]
instead of Debug-iphonesimulator directory:

```
$ xcrun lipo -info build/dylib/sim/Build/Products/Debug-iphoneos/calabash-dylib.dylib 
Architectures in the fat file: build/dylib/sim/Build/Products/Debug-iphoneos/calabash-dylib.dylib are: i386 x86_64 
```

**Comment by jmoody** [comment]
```
TARGET_BUILD_DIR="${BUILD_PRODUCTS_DIR}"                                                  
DWARF_DSYM_FOLDER_PATH="${BUILD_PRODUCTS_DIR}" 
```

**Comment by ohadschn** [comment]
Are these settings the workaround for this issue or simply your current setting with which it reproduces? Did you encounter any issues with the fact that it builds to the wrong folder or is it just a cosmetic oversight?

**Comment by jmoody** [comment]
100% confirmed that simulator targets are built to -iphoneos vs. -iphonesimulator.  Also happens when building non-library targets (like apps for the simulator).

The scripts fail because they expect binaries to be in a particular place.

> Are these settings the workaround for this issue or simply your current configuration with which it reproduces? 

I am debugging another (related) issue and found if I set those variables, I can coerce xcodebuild to produce the expected directories.

I will update the list in a moment.

**Comment by jmoody** [comment]
> Did you encounter any issues with the fact that it builds to the wrong folder or is it just a cosmetic oversight?

I don't know yet.  I suspect there will be a problem because the sim and arm Intermediate directory will be the same, but I cannot confirm.

**Comment by ohadschn** [comment]
Thanks for the speedy response! When you say "the scripts fail" do you mean calabash scripts or Apple scripts?

**Comment by jmoody** [comment]
The xcodebuild scripts.

The Calabash 0.17.0 libraries are fine; we built them with Xcode 7.1.

**Comment by ohadschn** [comment]
Oh, so what xcodebuild command exactly fails because of that (and with what error)? We've seen some failures with 7.2 and I'm wondering if they're related (I had to explicitly specify the VALID_ARCHS  flag).

**Comment by jmoody** [comment]
> We've seen some failures with 7.2 and I'm wondering if they're related

What are you building?

```
$ make dylibs
⚠️  ld: directory not found for option '-L/Users/moody/git/calabash/calabash-ios-server/build/dylib/sim/Build/Products/Debug-iphoneos'
⚠️  ld: directory not found for option '-F/Users/moody/git/calabash/calabash-ios-server/build/dylib/sim/Build/Products/Debug-iphoneos'
⚠️  ld: directory not found for option '-L/Users/moody/git/calabash/calabash-ios-server/build/dylib/sim/Build/Products/Debug-iphoneos'
⚠️  ld: directory not found for option '-F/Users/moody/git/calabash/calabash-ios-server/build/dylib/sim/Build/Products/Debug-iphoneos'
▸ Copying LPHTTPAsyncFileResponse.h
▸ Copying CalabashServer.h
▸ Copying LPCORSResponse.h
▸ Copying LPHTTPDataResponse.h
▸ Copying LPHTTPFileResponse.h
▸ Copying LPHTTPDynamicFileResponse.h
▸ Copying LPHTTPResponse.h
▸ Copying LPIsWebView.h
▸ Copying LPRoute.h
▸ Copying LPVersionRoute.h
▸ Copying LPWebQuery.h
▸ Copying LPRouter.h
▸ Copying LPWebViewProtocol.h
▸ Copying UIWebView+LPWebView.h
▸ Signing build/dylib/sim/Build/Products/Debug-iphoneos/calabash-dylib.dylib
▸ Build Succeeded
INFO: Building simulator library for framework succeeded.
ditto: can't get real path for source 'build/dylib/sim/Build/Products/Debug-iphonesimulator/calabash-dylib.dylib'
ERROR: Could not copy:
ERROR:   source: build/dylib/sim/Build/Products/Debug-iphonesimulator/calabash-dylib.dylib
ERROR:   target: Products/dylib/sim/calabash-dylib.dylib
ERROR: The source file does not exist
ERROR: Did a previous xcodebuild step fail?
ERROR: Exiting 1
make: *** [dylibs] Error 1
```

**Comment by ohadschn** [comment]
Oh nothing related to calabash, just our own application :) Thanks for the details, we'll be on the lookout if we encounter this issue.
