### ISSUE TITLE
Backgrounding app broken

### ISSUE THREAD

**Issue by jbelkins** [calabash/calabash-ios-server#348]
I am running Xcode 7.3 with the iPhone 6s / iOS 9.3 simulator.

With Calabash 0.18.1 `send_app_to_background` works for me.  In the console, I see:
```
irb(main):001:0> start_test_server_in_background
Calabash::Cucumber::Launcher: Launch Method instruments
Log file: <path omitted>
irb(main):002:0> send_app_to_background 1.0
{
    "duration" => 1
}
irb(main):003:0> query 'view'
<returns results...>
```
The sim returns to the home screen, then back into the app, as expected. Further commands are successful.
When using `send_app_to_background` in a feature spec, it works as well.
 
But when I updated Calabash to 0.18.2 (both the Cocoapod and the calabash-cucumber gem), it broke.
```
irb(main):001:0> start_test_server_in_background
 INFO: Detected app at path:
 INFO: <path omitted>
 INFO: Modification time of app: Thu 14 Apr 2016 12:15:57 CDT
 INFO: If this is incorrect, set the APP variable and/or rebuild your app
 INFO: It is your responsibility to ensure you are testing the right app.
Calabash::Cucumber::Launcher: Launch Method instruments
Log file: <path omitted>
irb(main):002:0> send_app_to_background 2.0
{
    "duration" => 2
}
irb(main):003:0> query 'view'
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (localhost:37265))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (localhost:37265))
Failing... Errno::ECONNREFUSED
<stack trace>
```
The sim goes to the home screen but does not return, and (presumably because the app is still backgrounded) does not accept any further connections from the console.

Apologies if this has already been identified, but I didn't see any related open issues.

Let me know if you need more info.  Thanks!

**Comment by jmoody** [comment]
+100 for an excellent bug report.

Our tests show background working on 0.19.0 (not released) and 0.18.2.

I am tempted to ask you to try to run this example: https://github.com/calabash/calabash-ios-server/blob/develop/cucumber/features/background.feature

but that will only tell you that background is working in 0.19.0.

If you are game, follow the directions in the README.

```
$ make app-cal
$ cd cucumber
$ bundle update
$ be cucumber -t @background
```

**Comment by jbelkins** [comment]
Your entire feature spec, including backgrounding, passes for me.  I'll stay locked on 0.18.2 until 0.19.0 releases.  Thanks for your help!

**Comment by jmoody** [comment]
@jbelkins I wonder what is going wrong.  There were no changes to the background API.

**Comment by jbelkins** [comment]
I can't reproduce this anymore - perhaps it was a configuration problem at my end.  Both your feature spec and mine now background & return just fine for me on 0.18.1 and 0.18.2.  Closing this issue.
