### ISSUE TITLE
Evaluate a batch of queries in a single webservice call 

### ISSUE THREAD

**Issue by yamkay** [calabash/calabash-ios-server#374]
Hi Team,

Since we do intensive validation for almost all view objects in a screen for each test scenario, it takes more time to complete each scenario due to the network latency in the webservice calls between calabash server and client.

Hence we came up with an idea to batch all the queries in a single request and send it to calabash server and validate the same batch and return the results. We have made the changes on our local copy and willing to contribute to the calabash repository.

I am getting this error while creating the branch feature/batch_query for raising the pull request.

remote: Permission to calabash/calabash-ios.git denied to yamkay.
fatal: unable to access 'https://github.com/calabash/calabash-ios-server.git/': The requested URL returned error: 403

Could you please guide the process for the same.

Thanks,
Mohan Kumar Selvaraj

**Comment by jmoody** [comment]
Can you provide an example?

> Since we do intensive validation for almost all view objects in a screen for each test scenario

I am not sure we want to encourage this kind of testing.  Let me see what my colleagues think.

**Comment by yamkay** [comment]
In our app, there are around 10 modal screens/popups that can come in any screen at any point of time during the test execution. Hence we need to validate the absence of all subviews of all modals/popup each time before the validation of the screen view objects. Each validation would cost a webservice call between server and client.

Currently the method "map" is used in Calabash for evaluating the query against the view objects of key window. Instead of sending one query in a webservice call, we can send multiple queries in a batch and then validate all the queries in calabash server and send the results back to calabash ruby client.

**Comment by jmoody** [comment]
Why don't you call:

```
query("*")
```

and parse the results?

**Comment by yamkay** [comment]
Initially we had thought about this idea to query all the elements in the screen and match the required one. In majority of the screens, we have more than one view objects with same accessibility  label or id. Hence we need to identify each view object with the parent or children relationships. Since the query("*") lists the array of view objects in JSON format, it doesn't give any information about the hierarchy or relationship between the view objects.

Therefore, we had dropped this one and worked on batch query.

**Comment by jmoody** [comment]
I don't think we are interested in this feature.

We might be interested in a single query that returns JSON with view hierarchies preserved.
