### ISSUE TITLE
Incorrect iPad Pro Screen Dimensions

### ISSUE THREAD

**Issue by infomaniac50** [calabash/calabash-ios-server#388]
I'm using the iPad Pro simulator to run my app and the screenshots are all the wrong size. The screenshots are 1536w by 2048h. It's a 12.7 inch device that's being simulated and the simulators built in screenshots are 2048w by 2732h. 

http://help.apple.com/itunes-connect/developer/#/devd274dd925 says  

> 12.9-Inch Retina Display  
> 2048 x 2732 pixels for portrait  
> 2732 x 2048 pixels for landscape  
> Required if app runs on iPad

I'm not sure why ``screen_dimensions`` says otherwise. I think this might be messing up ``touch`` too. I'm building a hybrid app using cordova but the touches seem to happen in the wrong spot. ``touch`` works good on the iPhone 7 Plus device.

``server_version`` shows:
```
{
                  "device_family" => "iPad",
                        "outcome" => "SUCCESS",
                    "server_port" => 37265,
               "simulator_device" => "",
                      "simulator" => "CoreSimulator 375.21 - Device: iPad Pro (12.9 inch) - Runtime: iOS 10.3 (14E8301) - DeviceType: iPad Pro (12.9-inch)",
                       "app_name" => "Heartland Soccer Mobile",
                    "app_version" => "0.8.0",
              "screen_dimensions" => {
        "native_scale" => 2,
              "sample" => 1,
              "height" => 2048,
               "width" => 1536,
               "scale" => 2
    },
                            "git" => {
             "revision" => "dc15597",
        "remote_origin" => "git@github.com:calabash/calabash-ios-server.git",
               "branch" => "master"
    },
                    "device_name" => "A1278-C1MJV1QKDTY4",
                          "4inch" => false,
                         "app_id" => "net.heartlandsoccer.m",
                    "form_factor" => "ipad pro",
                         "system" => "x86_64",
                        "version" => "0.20.4",
                    "iOS_version" => "10.3.1",
           "short_version_string" => "0.8.0",
                    "ios_version" => "10.3.1",
    "iphone_app_emulated_on_ipad" => false,
               "model_identifier" => "iPad6,8",
                   "app_base_sdk" => "iphonesimulator10.3"
}
```

**Comment by jmoody** [comment]
Thanks for reporting. I added this to my queue for this week.

**Comment by jmoody** [comment]
```
# After adding the new device models

 "screen_dimensions": {
        "native_scale": 2,
        "sample": 1,
        "height": 2732,
        "width": 2048,
        "scale": 2
    },

$ file screenshot_0.png 
screenshot_0.png: PNG image data, 2048 x 2732, 8-bit/color RGBA, non-interlaced
```

**Comment by jmoody** [comment]
> I'm building a hybrid app using cordova but the touches seem to happen in the wrong spot.

I have not been able to reproduce this problem on iPad Pro 12.7" models.

I did reproduce touch coordinate problems on an iPad Pro 10.5" - see #390.

If you have touch problems, please open a new issue with steps to reproduce.

Thanks!
