### ISSUE TITLE
calabash-ios-server contains iOS9.0 deprecated defines and methods

### ISSUE THREAD

**Issue by sarastro-nl** [calabash/calabash-ios-server#398]
kCFStreamNetworkServiceTypeVoIP is deprecated in LPGCDAsyncSocket.m: 
 r1 = CFReadStreamSetProperty(readStream, kCFStreamNetworkServiceType, kCFStreamNetworkServiceTypeVoIP);
  r2 = CFWriteStreamSetProperty(writeStream, kCFStreamNetworkServiceType, kCFStreamNetworkServiceTypeVoIP);

stringByReplacingPercentEscapesUsingEncoding is deprecated in LPUIAUserPrefsChannel.m:
    path = [[unsanitizedPlistPath stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding] copy];

**Comment by jmoody** [comment]
Thank you.  We may or may not address these issues.
