### ISSUE TITLE
"calabash-ios download" fails with 301: Access Denied

### ISSUE THREAD

**Issue by garyjohnson** [calabash/calabash-ios-server#405]
Trying to download the calabash.framework via `calabash-ios download` attempts to download from http://cloud.github.com/downloads/calabash/calabash-ios/calabash.framework-0.9.111.zip, which returns the following payload:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>00E194C62A076451</RequestId>
<HostId>
UzqPqftbPd1A9niY/BmmfOdrPUHVp8AGyzQSSohO7qNVGc22HEaT2aui2lNATUJohulmu6KXdUI=
</HostId>
</Error>
```

In the terminal, this is the output:
```
Did not find calabash.framework. I'll download it...'
http://cloud.github.com/downloads/calabash/calabash-ios/calabash.framework-0.9.111.zip
Got bad response code 301.
Aborting...
```

**Comment by garyjohnson** [comment]
No longer occurs, download now completes successfully.

**Comment by jmoody** [comment]
That framework is many years out of date.  The most recent calabash.framework is bundled in the calabash-cucumber gem.
