### ISSUE TITLE
Cannot invoke recordApplicationEvent method

### ISSUE THREAD

**Issue by bd9142** [calabash/calabash-ios-server#440]
Hello, 

I am interested in how calabash works. I want to learn details of calabash ios server. So, i looked into source code and i want to ask something about source code. I found 

`record `  and `recordApplicationEvent`  method in calabash/Classes/FranklyServer/LPRecorder.m file. I want to learn how they work.
Firstly:
1. I found http request to start record. However, i could not understand which method (get,post..) and params needed to invoke record method ? Do i need another iOS application to do requests ?
2. I invoked record method when calabash starts manually. However, recordApplicationEvent method is not called when i press button and do something in UI.(I guess it has to be invoked by OS - UIApplication) How to invoke recordApplicationEvent to record gestures ? Does iOS support this event invoking and handling ?

Thank you .

**Comment by jmoody** [comment]
The LPRecorder stopped working with iOS 7.

We switched to UIAutomation to perform gestures - which worked until iOS 9.

Now we use DeviceAgent - a custom XCUITest application that allows us to create events to generate gestures.  That is open source:  https://github.com/calabash/DeviceAgent.iOS

The LP server is used to analyze the view hierarchy of the app and perform backdoor calls.

**Comment by bd9142** [comment]
Thank you for response @jmoody . :)
